---
# tasks file for svn

- name: Set dir_info,pkg_info fact in {{ ansible_distribution }} by {{ svn_install_type }} install
  set_fact:
    dir_info: "{{ svn_dirs[ansible_os_family] }}"
    pkg_info: "{{ svn_packages[svn_version][ansible_os_family] }}"

- name: Include Windows-{{ svn_install_type }}.yml in {{ ansible_distribution }} by {{ svn_install_type }} install
  include: Window-{{ svn_install_type }}.yml
